services:
  hello-world:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-world-app
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m
      - LOG_LEVEL=INFO
    ports:
      - "8080:8080"  # In case you add HTTP endpoints later 